### ISSUE TITLE
Consider autoformatter

### ISSUE THREAD

**Issue by jcpunk** [DUNE-DAQ/justintime#24]
Something like `pre-commit` could help ensure consistent style across the various files in an automated fashion.

For example:
```yaml
#.pre-commit-config.yaml
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-toml
  - repo: "https://github.com/pycqa/isort"
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: "https://github.com/psf/black"
    rev: 22.3.0
    hooks:
      - id: black
  - repo: "https://github.com/asottile/pyupgrade"
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args:
          - "--py310-plus"
  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude_types:
          - "python"
        additional_dependencies:
          - "prettier"
          - "prettier-plugin-toml@0.3.1"
```
and
```
#pyproject.toml
[tool.black]
line-length = 120
target-version = ['py310']

[tool.isort]
src_paths = ["src", "test"]
py_version = 310
profile = "black"
line_length = 120
combine_star = "True"
float_to_top = "True"
order_by_type = "True"
dedup_headings = "True"
lines_between_types = 1
force_alphabetical_sort_within_sections = "True"
```
Along with:
```yaml
#.github/workflows/pre-commit.yml
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
```

Would generate a fairly massive initial diff, but result in highly consistent code formatting across the project.
